### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by NolanPG** [Armando-J/post_bot#5]
Los palabras de los tags en la publicación se generan separadas ("#hola mundo" en lugar de "#hola_mundo"), dependiendo del código se podría (o no) solucionar de una forma similar a esta:

var_1 = "hola mundo, spam eggs, var replace"
var_2 = var_1.replace(" ", "_")
var_3 = var_2.replace(",_", ", ")
print(var_3)
>>>hola_mundo, spam_eggs, var_replace

**Comment by Armando-J** [comment]
Gracias .
Debe estar resuelto en https://github.com/Armando-J/post_bot/commit/b5208d4faadcb3008cd671dc7f3b9083b052cd46
